INSERT INTO WORDS (name, mean) VALUES
("afraid", "두려워하다"),
("afternoon", "오후"),
("again", "다시"),
("ago", "전에"),
("air", "공기"),
("all", "모두 모든"),
("almost", "거의"),
("already", "이미"),
("also", "역시"),
("always", "언제나"),
("animal", "동물"),
("another", "또다른"),
("answer", "답변"),
("any", "어떠한"),
("apple", "사과"),
("ask", "묻다 질문하다"),
("aunt", "아주머니"),
("away", "멀리"),
("baby", "아기"),
("back", "뒤 등"),
("bad", "나쁜"),
("bag", "가방"),
("ball", "공기"),
("baseball", "야구"),
("basketball", "농구"),
("be", "이다 있다"),
("beautiful", "아름다운"),
("become", "되다"),
("bed", "침대"),
("begin", "시작하다"),
("believe", "믿다"),
("big", "큰"),
("bike", "자전거"),
("bill", "영수증"),
("bird", "새"),
("birthday", "생일"),
("body", "몸"),
("book", "책"),
("both", "둘다"),
("boy", "소년"),
("breakfast", "아침식사"),
("brother", "남자형제"),
("brown", "갈색"),
("building", "건물"),
("bus", "버스"),
("busy", "바쁜"),
("buy", "사다 구입하다"),
("cake", "케익"),
("call", "부르다 전화하다"),
("can", "할수있다"),
("car", "자동차"),
("care", "돌보다 신경쓰다"),
("certainly", "확실히"),
("change", "바꾸다"),
("child", "어린이"),
("city", "도시"),
("class", "급 학급"),
("clean", "깨끗한"),
("clock", "시계"),
("clothes", "옷"),
("club", "동아리 클럽"),
("cold", "차가운"),
("come", "오다"),
("computer", "컴퓨터"),
("country", "나라 시골"),
("course", "경로 코스"),
("daughter", "딸"),
("day", "날"),
("dear", "친애하는"),
("desk", "책상"),
("dialog", "대화"),
("diary", "일기장"),
("different", "다른"),
("dinner", "저녁식사"),
("do", "하다"),
("doctor", "의사"),
("dog", "개"),
("donkey", "당나귀"),
("door", "문"),
("down", "아래로"),
("dream", "꿈"),
("dress", "옷 옷을입다"),
("driver", "운전사"),
("each", "각각의"),
("early", "이른"),
("earth", "지구"),
("easy", "쉬운"),
("eat", "먹다"),
("end", "끝 끝나다"),
("enough", "충분한"),
("evening", "저녁"),
("every", "모든"),
("everybody", "모든사람"),
("example", "예시"),
("excuse", "사과하다"),
("eye", "눈"),
("family", "가족"),
("far", "먼"),
("farmer", "농부"),
("fast", "빠른"),
("father", "아버지"),
("feel", "느끼다 느낌"),
("few", "거의없는"),
("field", "들판 장 필드"),
("find", "찾다"),
("fine", "좋은 미세한"),
("fire", "불"),
("first", "첫번째"),
("fish", "물고기"),
("flower", "꽃"),
("food", "음식"),
("friend", "친구"),
("front", "앞의"),
("fun", "재미있는"),
("futher", "먼"),
("game", "경기"),
("gesture", "제스쳐 몸동작"),
("get", "얻다"),
("girl", "소녀"),
("give", "주다"),
("glad", "기쁜"),
("gold", "금"),
("good", "좋은"),
("grandfather", "할아버지"),
("grandparent", "조부모"),
("great", "훌륭한"),
("hand", "손"),
("happy", "행복한"),
("hard", "어려운"),
("have", "가지다"),
("he", "그 그남자"),
("health", "건강"),
("hear", "듣다"),
("help", "도와주다"),
("here", "여기"),
("high", "높은"),
("history", "역사"),
("hobby", "취미"),
("home", "집 가정"),
("hometown", "고향"),
("homework", "숙제"),
("hope", "희망하다 희망"),
("hot", "뜨거운"),
("hour", "시간"),
("house", "집"),
("however", "그러나"),
("hurry", "서두르는"),
("idea", "생각 아이디어"),
("important", "중요한"),
("interesting", "재미있는"),
("it", "그것"),
("job", "직업"),
("just", "단지"),
("keep", "유지하다"),
("kind", "친절한 종류"),
("king", "왕"),
("know", "알다"),
("land", "땅"),
("language", "언어"),
("large", "큰"),
("last", "마지막 지속하다"),
("late", "늦은"),
("later", "나중에"),
("leaf", "나뭇잎"),
("learn", "배우다"),
("lesson", "레슨"),
("let", "시키다 하게하다"),
("letter", "편지"),
("life", "삶"),
("light", "빛 가벼운"),
("like", "좋아하다"),
("line", "선"),
("listen", "듣다 (귀기울여)"),
("little", "작은"),
("live", "살다 살아있는"),
("long", "긴"),
("look", "보다"),
("lot", "많은"),
("love", "사랑하다 사랑"),
("lunch", "점심식사"),
("make", "만들다"),
("man", "남자 사람"),
("manner", "매너 행동양식"),
("many", "많은 (셀수있는)"),
("matter", "문제"),
("maybe", "어쩌면 아마"),
("mean", "의미하다 평균의"),
("meet", "만나다"),
("middle", "가운데"),
("mind", "마음 꺼리다"),
("minute", "분 (시간)"),
("miss", "그리워하다"),
("money", "돈"),
("month", "달 (날짜)"),
("moon", "달 (하늘에 있는)"),
("morning", "아침"),
("mother", "어머니"),
("mountain", "산"),
("mouse", "쥐"),
("movie", "영화"),
("much", "많은 (셀수없는)"),
("music", "음악"),
("name", "이름"),
("nature", "자연"),
("never", "결코 아닌"),
("new", "새로운"),
("newspaper", "신문"),
("next", "다음의 다음"),
("nice", "좋은 훌륭한"),
("night", "밤"),
("north", "북쪽 북쪽의"),
("now", "지금"),
("number", "숫자"),
("office", "사무실"),
("often", "종종"),
("old", "오래된"),
("once", "한번"),
("oneself", "자기자신"),
("only", "단지 그것뿐인"),
("other", "다른"),
("outside", "바깥의"),
("owl", "올빼미"),
("paper", "종이"),
("parent", "부모님"),
("park", "공원 주차하다"),
("part", "조각 부분"),
("party", "파티 일행 정당"),
("pen", "펜"),
("people", "사람들 민족"),
("person", "사람"),
("picture", "그림"),
("place", "장소"),
("plane", "평명"),
("play", "놀다 운동하다"),
("please", "기쁜 기쁘게하다 제발"),
("policeman", "경찰관"),
("pollution", "오염"),
("present", "선물 오늘 현재"),
("pretty", "귀여운 꽤"),
("prince", "왕자"),
("problem", "문제"),
("question", "문제"),
("quickly", "재빠르게"),
("race", "경주 인종"),
("rain", "비"),
("read", "읽다"),
("really", "정말로"),
("refrigerator", "냉장고"),
("remember", "기억하다"),
("rice", "쌀"),
("right", "오른쪽 올바른"),
("river", "강"),
("room", "방"),
("rule", "규칙"),
("sad", "슬픈"),
("same", "같은"),
("Saturday", "토요일"),
("say", "말하다"),
("school", "학교"),
("science", "과학"),
("sea", "바다"),
("season", "계절 시즌"),
("second", "두번째 초(시간)"),
("see", "보다"),
("September", "9월"),
("she", "그녀"),
("ship", "배"),
("shoe", "신발"),
("show", "보여주다 쇼"),
("side", "옆"),
("sign", "사인 부호"),
("sing", "노래부르다"),
("sister", "자매 여형제"),
("sky", "하늘"),
("small", "작은"),
("snow", "눈(하늘에서 날리는)"),
("soccer", "축구"),
("some", "어느정도의"),
("something", "어떤것"),
("sometimes", "때때로"),
("son", "아들"),
("song", "노래"),
("soon", "곧"),
("sorry", "미안한"),
("sound", "소리"),
("south", "남쪽 남쪽의"),
("space", "공간"),
("speak", "말하다"),
("sport", "운동"),
("spring", "봄 스프링"),
("still", "여전히"),
("stone", "돌맹이"),
("stop", "멈추다"),
("store", "상점"),
("street", "거리"),
("student", "학생"),
("subway", "지하철"),
("such", "그런"),
("summer", "여름"),
("sun", "태양"),
("Sunday", "일요일"),
("sure", "확실한"),
("table", "테이블 탁자"),
("talk", "대화하다"),
("tall", "키가큰"),
("teacher", "선생님"),
("team", "팀"),
("tell", "말하다"),
("tennis", "테니스"),
("thank", "감사하다"),
("that", "저것"),
("there", "거기"),
("they", "그들"),
("think", "생각하다"),
("this", "이것"),
("time", "시간"),
("tired", "지친"),
("today", "오늘"),
("together", "함께"),
("tomorrow", "내일"),
("too", "역시"),
("tower", "타워"),
("town", "마을"),
("train", "기차"),
("tree", "나무"),
("trip", "여행"),
("try", "시도하다"),
("uncle", "삼촌"),
("up", "위로"),
("use", "사용하다"),
("usually", "보통"),
("vacation", "방학"),
("very", "매우"),
("village", "마을"),
("walk", "걷다"),
("want", "원하다"),
("warm", "따뜻한"),
("waste", "낭비하다"),
("watch", "주시하다 시계"),
("water", "물"),
("way", "길"),
("we", "우리"),
("week", "주 (일주일)"),
("welcome", "환영하다"),
("well", "좋은"),
("white", "하얀"),
("wife", "아내"),
("will", "할것이다"),
("window", "창문"),
("winter", "겨울"),
("wish", "소망하다"),
("woman", "여자"),
("wonderful", "훌륭한"),
("word", "단어"),
("world", "세계 세상"),
("write", "글을쓰다"),
("year", "년(일년)"),
("yesterday", "어제"),
("you", "당신"),
("young", "어린")
